codecov:
  notify:
    after_n_builds: 10
comment:
  after_n_builds: 10
ignore:
  - "vendor"
  - "bin"
  - "**/*.svg"
  - "lib/sitemap_generator"
  - "lib/generators"
flag_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 1%
